/* pe-e - Baseline Configuration */
/* Role: PE Router, DC: east */

system {
    host-name pe-e;
    services {
        ssh;
        netconf {
            ssh;
        }
    }
}

interfaces {
    et-0/0/0 {
        description "to rr1";
        mtu 9200;
        unit 0 {
            family inet {
                address 10.0.0.5/31;
            }
            family inet6 {
                address fd00:0:2::1/127;
            }
            family iso;
            family mpls;
        }
    }
    et-0/0/1 {
        description "to rr2";
        mtu 9200;
        unit 0 {
            family inet {
                address 10.0.0.9/31;
            }
            family inet6 {
                address fd00:0:4::1/127;
            }
            family iso;
            family mpls;
        }
    }
    et-0/0/2 {
        description "to bl-e";
        mtu 9200;
        unit 0 {
            family inet {
                address 10.2.0.4/31;
            }
            family inet6 {
                address fd00:2:2::0/127;
            }
            family iso;
            family mpls;
        }
    }
    et-0/0/3 {
        description "to bl-e";
        mtu 9200;
        unit 0 {
            family inet {
                address 10.2.0.6/31;
            }
            family inet6 {
                address fd00:2:3::0/127;
            }
            family iso;
            family mpls;
        }
    }
    et-0/0/4 {
        description "to client-e";
        mtu 9200;
        unit 0 {
            family inet {
                address 10.100.2.0/31;
            }
            family inet6 {
                address fd00:100:2::0/127;
            }
            family iso;
            family mpls;
        }
    }
    et-0/0/5 {
        description "to pe-w";
        mtu 9200;
        unit 0 {
            family inet {
                address 10.0.0.11/31;
            }
            family inet6 {
                address fd00:0:5::1/127;
            }
            family iso;
            family mpls;
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 10.255.0.13/32;
            }
            family inet6 {
                address fd00::13/128;
            }
            family iso {
                address 49.0001.0102.5500.0013.00;
            }
        }
    }
}