set version 25.2R1.8-EVO
set system host-name pe-e
set system root-authentication encrypted-password "$6$rounds=656000$BId6TF.0oLKTuvDi$Oxd538vLe2vOj8G6rYL.bumt9YkUo2xCE.kUU/MsdLB4JWkL/OtEltvY3acIpSmsxfjPMdC22TcZP.WGV3WJQ1"
set system login user admin uid 2000
set system login user admin class super-user
set system login user admin authentication encrypted-password "$6$rounds=656000$BId6TF.0oLKTuvDi$Oxd538vLe2vOj8G6rYL.bumt9YkUo2xCE.kUU/MsdLB4JWkL/OtEltvY3acIpSmsxfjPMdC22TcZP.WGV3WJQ1"
set system services netconf ssh
set system services ssh root-login allow
set system management-instance
set interfaces et-0/0/0 description "to rr1"
set interfaces et-0/0/0 mtu 9200
set interfaces et-0/0/0 unit 0 family inet address 10.0.0.5/31
set interfaces et-0/0/0 unit 0 family iso
set interfaces et-0/0/0 unit 0 family inet6 address fd00:0:2::1/127
set interfaces et-0/0/0 unit 0 family mpls
set interfaces et-0/0/1 description "to rr2"
set interfaces et-0/0/1 mtu 9200
set interfaces et-0/0/1 unit 0 family inet address 10.0.0.9/31
set interfaces et-0/0/1 unit 0 family iso
set interfaces et-0/0/1 unit 0 family inet6 address fd00:0:4::1/127
set interfaces et-0/0/1 unit 0 family mpls
set interfaces et-0/0/2 description "to bl-e"
set interfaces et-0/0/2 mtu 9200
set interfaces et-0/0/2 unit 0 family inet address 10.2.0.4/31
set interfaces et-0/0/2 unit 0 family iso
set interfaces et-0/0/2 unit 0 family inet6 address fd00:2:2::0/127
set interfaces et-0/0/2 unit 0 family mpls
set interfaces et-0/0/3 description "to bl-e"
set interfaces et-0/0/3 mtu 9200
set interfaces et-0/0/3 unit 0 family inet address 10.2.0.6/31
set interfaces et-0/0/3 unit 0 family iso
set interfaces et-0/0/3 unit 0 family inet6 address fd00:2:3::0/127
set interfaces et-0/0/3 unit 0 family mpls
set interfaces et-0/0/4 description "to client-e"
set interfaces et-0/0/4 mtu 9200
set interfaces et-0/0/4 unit 0 family inet address 10.100.2.0/31
set interfaces et-0/0/4 unit 0 family iso
set interfaces et-0/0/4 unit 0 family inet6 address fd00:100:2::0/127
set interfaces et-0/0/4 unit 0 family mpls
set interfaces et-0/0/5 description "to pe-w"
set interfaces et-0/0/5 mtu 9200
set interfaces et-0/0/5 unit 0 family inet address 10.0.0.11/31
set interfaces et-0/0/5 unit 0 family iso
set interfaces et-0/0/5 unit 0 family inet6 address fd00:0:5::1/127
set interfaces et-0/0/5 unit 0 family mpls
set interfaces lo0 unit 0 family inet address 10.255.0.13/32
set interfaces lo0 unit 0 family iso address 49.0001.0102.5500.0013.00
set interfaces lo0 unit 0 family inet6 address fd00::13/128
set interfaces re0:mgmt-0 unit 0 family inet address 10.0.0.15/24
set interfaces re0:mgmt-0 unit 0 family inet6 address 2001:db8::2/64
set routing-instances mgmt_junos routing-options rib mgmt_junos.inet6.0 static route ::/0 next-hop 2001:db8::1
set routing-instances mgmt_junos routing-options static route 0.0.0.0/0 next-hop 10.0.0.2
set protocols isis interface et-0/0/5.0 level 1 disable
set protocols isis interface lo0.0 passive
set protocols isis source-packet-routing srgb start-label 16000
set protocols isis source-packet-routing srgb index-range 8000
set protocols isis source-packet-routing node-segment ipv4-index 13
set protocols isis source-packet-routing node-segment ipv6-index 113
set protocols isis level 1 disable
set protocols isis level 2 wide-metrics-only
set protocols mpls interface et-0/0/5.0
set protocols mpls interface lo0.0
