
> show running-config
! Command: show running-config at line 1
! device: bl-e (cEOSLab, EOS-4.35.1F-45319759.4351F (engineering build))
!
no aaa root
!
username admin privilege 15 role network-admin secret sha512 $6$MtTtNqvTLpAsYoiI$PQr1TNbLlP0O.sZuPV/0MO8Rk4xO41eMEj55D0E0LigqSPjBeqy4RaIBHAWjiLUQaJ3y/4X35uasBxgKnjQI/0
!
management api http-commands
   no shutdown
!
no service interface inactive port-id allocation disabled
!
service routing protocols model multi-agent
!
hostname bl-e
!
spanning-tree mode mstp
!
system l1
   unsupported speed action error
   unsupported error-correction action error
!
vlan 4001
!
vrf instance CDN
!
interface Ethernet1
   description to-spine-e
   mtu 9214
   no switchport
   ip address 10.1.20.5/31
   ipv6 address fd00:1:22::1/127
   ip ospf network point-to-point
!
interface Ethernet2
   description to-spine-e
   mtu 9214
   no switchport
   ip address 10.1.20.7/31
   ipv6 address fd00:1:23::1/127
   ip ospf network point-to-point
!
interface Ethernet3
   description to-pe-e
   mtu 9214
   no switchport
   vrf CDN
   ip address 10.2.0.5/31
   ipv6 address fd00:2:2::1/127
!
interface Ethernet4
   description to-pe-e
   mtu 9214
   no switchport
   vrf CDN
   ip address 10.2.0.7/31
   ipv6 address fd00:2:3::1/127
!
interface Loopback0
   ip address 10.255.30.21/32
   ipv6 address fd00:30::21/128
!
interface Loopback1
   description VTEP
   ip address 10.255.31.21/32
!
interface Loopback100
   vrf CDN
   ip address 198.51.100.1/32
   ipv6 address 2001:db8:cafe::1/128
!
interface Management0
   ip address 172.20.20.36/24
   ipv6 address 3fff:172:20:20::24/64
!
interface Vlan4001
   vrf CDN
   ip address virtual 169.254.1.1/24
!
ip routing
ip routing vrf CDN
!
ipv6 unicast-routing
ipv6 unicast-routing vrf CDN
!
router multicast
   ipv4
      software-forwarding kernel
   !
   ipv6
      software-forwarding kernel
!
router ospf 1
   router-id 10.255.30.21
   passive-interface default
   no passive-interface Ethernet1
   no passive-interface Ethernet2
   network 10.1.20.4/31 area 0.0.0.0
   network 10.1.20.6/31 area 0.0.0.0
   network 10.255.30.21/32 area 0.0.0.0
   network 10.255.31.21/32 area 0.0.0.0
   max-lsa 12000
!
end
