! l1-w - Baseline Configuration
! Role: leaf, DC: west

hostname l1-w

! Management
service routing protocols model multi-agent
management api http-commands
   no shutdown

! Local user for eAPI access
username admin privilege 15 role network-admin secret admin123

! Global routing
ip routing
ipv6 unicast-routing

! Loopback
interface Loopback0
   ip address 10.255.10.11/32
   ipv6 address fd00:10::11/128

interface Loopback1
   description VTEP
   ip address 10.255.11.11/32

! P2P to spine-w
interface Ethernet1
   description to-spine-w
   no switchport
   mtu 9214
   ip address 10.1.0.1/31
   ipv6 address fd00:1:0::1/127
