
> show running-config
! Command: show running-config at line 1
! device: l1-w (cEOSLab, EOS-4.35.1F-45319759.4351F (engineering build))
!
no aaa root
!
username admin privilege 15 role network-admin secret sha512 $6$lJsX5GH0Z/LjygeZ$GHBOT9lUUYFIhLgfHUB/hDO.72ZGq6/cIcJcNhA3CG0KIgCAninVDlB5O5dfB1TEbBRyU.FSHUL5kIXl0wAz..
!
management api http-commands
   no shutdown
!
no service interface inactive port-id allocation disabled
!
service routing protocols model multi-agent
!
hostname l1-w
!
spanning-tree mode mstp
!
system l1
   unsupported speed action error
   unsupported error-correction action error
!
vlan 10-11
!
vlan 4001
   trunk group L3VNI-BUNDLE
!
vrf instance CDN
!
interface Ethernet1
   description to-spine-w
   mtu 9214
   no switchport
   ip address 10.1.0.1/31
   ipv6 address fd00:1::1/127
   ip ospf network point-to-point
!
interface Ethernet3
   description to-h1-w
   switchport access vlan 10
!
interface Loopback0
   ip address 10.255.10.11/32
   ipv6 address fd00:10::11/128
!
interface Loopback1
   description VTEP
   ip address 10.255.11.11/32
!
interface Management0
   ip address 172.20.20.37/24
   ipv6 address 3fff:172:20:20::25/64
!
interface Vlan10
   vrf CDN
   ip address virtual 192.168.10.1/24
   ipv6 address virtual 2001:db8:10::1/64
!
interface Vlan11
   vrf CDN
   ip address virtual 192.168.11.1/24
   ipv6 address virtual 2001:db8:11::1/64
!
interface Vlan4001
   vrf CDN
   ip address virtual 169.254.1.1/24
!
ip virtual-router mac-address 00:1c:73:00:00:99
!
ip routing
ip routing vrf CDN
!
ipv6 unicast-routing
ipv6 unicast-routing vrf CDN
!
router multicast
   ipv4
      software-forwarding kernel
   !
   ipv6
      software-forwarding kernel
!
router ospf 1
   router-id 10.255.10.11
   passive-interface default
   no passive-interface Ethernet1
   network 10.1.0.0/31 area 0.0.0.0
   network 10.255.10.11/32 area 0.0.0.0
   network 10.255.11.11/32 area 0.0.0.0
   max-lsa 12000
!
end
