
> show running-config
! Command: show running-config at line 1
! device: l1-w (cEOSLab, EOS-4.35.1F-45319759.4351F (engineering build))
!
no aaa root
!
username admin privilege 15 role network-admin secret sha512 $6$lJsX5GH0Z/LjygeZ$GHBOT9lUUYFIhLgfHUB/hDO.72ZGq6/cIcJcNhA3CG0KIgCAninVDlB5O5dfB1TEbBRyU.FSHUL5kIXl0wAz..
!
management api http-commands
   no shutdown
!
no service interface inactive port-id allocation disabled
!
service routing protocols model multi-agent
!
logging host 10.255.0.100
logging source-interface Loopback0
!
hostname l1-w
!
snmp-server engineID local f5717f001c735e603800
snmp-server view CDN-VIEW iso included
snmp-server group CDN-GRP v3 priv read CDN-VIEW
snmp-server user cdnmon CDN-GRP v3 localized f5717f001c735e603800 auth sha f2bcbc5482039e3c8ed59da2ac7c49a0ea7b27b0 priv aes fdc7c81acdaf95078d6ec59570043371
!
spanning-tree mode mstp
!
system l1
   unsupported speed action error
   unsupported error-correction action error
!
vlan 10-11
!
vlan 4001
   trunk group L3VNI-BUNDLE
!
vrf instance CDN
!
aaa authentication login console local
aaa authorization exec default local
!
interface Ethernet1
   description to-spine-w
   mtu 9214
   no switchport
   ip address 10.1.0.1/31
   ipv6 address fd00:1::1/127
   ip ospf network point-to-point
!
interface Ethernet3
   description to-h1-w
   switchport access vlan 10
!
interface Loopback0
   ip address 10.255.10.11/32
   ipv6 address fd00:10::11/128
!
interface Loopback1
   description VTEP
   ip address 10.255.11.11/32
!
interface Management0
   ip address 172.20.20.37/24
   ipv6 address 3fff:172:20:20::25/64
!
interface Vlan10
   vrf CDN
   ip address virtual 192.168.10.1/24
   ipv6 address virtual 2001:db8:10::1/64
!
interface Vlan11
   vrf CDN
   ip address virtual 192.168.11.1/24
   ipv6 address virtual 2001:db8:11::1/64
!
interface Vlan4001
   vrf CDN
   ip address virtual 169.254.1.1/24
!
interface Vxlan1
   vxlan source-interface Loopback1
   vxlan udp-port 4789
   vxlan vlan 10 vni 10010
   vxlan vlan 11 vni 10011
   vxlan vrf CDN vni 50100
!
ip virtual-router mac-address 00:1c:73:00:00:99
!
ip routing
ip routing vrf CDN
!
ipv6 unicast-routing
ipv6 unicast-routing vrf CDN
!
router bgp 65100
   router-id 10.255.10.11
   no bgp default ipv4-unicast
   neighbor 10.255.10.1 remote-as 65100
   neighbor 10.255.10.1 update-source Loopback0
   neighbor 10.255.10.1 send-community extended
   !
   vlan-aware-bundle CDN_BUNDLE
      rd 10.255.10.11:20100
      route-target both 65100:20100
      redistribute learned
      vlan 10-11,4001
   !
   address-family evpn
      neighbor 10.255.10.1 activate
   !
   vrf CDN
      rd 10.255.10.11:100
      route-target import evpn 65000:100
      route-target export evpn 65000:100
      router-id 10.255.10.11
      redistribute connected
!
router multicast
   ipv4
      software-forwarding kernel
   !
   ipv6
      software-forwarding kernel
!
router ospf 1
   router-id 10.255.10.11
   passive-interface default
   no passive-interface Ethernet1
   network 10.1.0.0/31 area 0.0.0.0
   network 10.255.10.11/32 area 0.0.0.0
   network 10.255.11.11/32 area 0.0.0.0
   max-lsa 12000
!
end
