! l2-e - Baseline Configuration
! Role: leaf, DC: east

hostname l2-e

! Management
service routing protocols model multi-agent
management api http-commands
   no shutdown

! Local user for eAPI access
username admin privilege 15 role network-admin secret admin123

! Global routing
ip routing
ipv6 unicast-routing

! Loopback
interface Loopback0
   ip address 10.255.30.12/32
   ipv6 address fd00:30::12/128

interface Loopback1
   description VTEP
   ip address 10.255.31.12/32

! P2P to spine-e
interface Ethernet1
   description to-spine-e
   no switchport
   mtu 9214
   ip address 10.1.20.3/31
   ipv6 address fd00:1:21::1/127
