
> show running-config
! Command: show running-config at line 1
! device: l2-w (cEOSLab, EOS-4.35.1F-45319759.4351F (engineering build))
!
no aaa root
!
username admin privilege 15 role network-admin secret sha512 $6$8X6FFGuoMqbLG0Bk$qRkk0bEXefELCSOLnYjmJU251aBF.0Y0Ctu99j0KVVZYYo.FPEXpaYOYmizroEPBfg2S/Pd0DcJ0k/65I0iON0
!
management api http-commands
   no shutdown
!
no service interface inactive port-id allocation disabled
!
service routing protocols model multi-agent
!
hostname l2-w
!
spanning-tree mode mstp
!
system l1
   unsupported speed action error
   unsupported error-correction action error
!
interface Ethernet1
   description to-spine-w
   mtu 9214
   no switchport
   ip address 10.1.0.3/31
   ipv6 address fd00:1:1::1/127
   ip ospf network point-to-point
   ip ospf area 0.0.0.0
   ospfv3 ipv6 network point-to-point
   ospfv3 ipv6 area 0.0.0.0
!
interface Ethernet3
!
interface Loopback0
   ip address 10.255.10.12/32
   ipv6 address fd00:10::12/128
   ip ospf area 0.0.0.0
   ospfv3 ipv6 area 0.0.0.0
!
interface Loopback1
   description VTEP
   ip address 10.255.11.12/32
   ip ospf area 0.0.0.0
!
interface Management0
   ip address 172.20.20.29/24
   ipv6 address 3fff:172:20:20::1d/64
!
ip routing
!
ipv6 unicast-routing
!
router bgp 65100
   router-id 10.255.10.12
   no bgp default ipv4-unicast
   maximum-paths 4 ecmp 4
   neighbor 10.255.10.1 remote-as 65100
   neighbor 10.255.10.1 update-source Loopback0
   neighbor 10.255.10.1 send-community extended
   !
   address-family evpn
      neighbor 10.255.10.1 activate
!
router multicast
   ipv4
      software-forwarding kernel
   !
   ipv6
      software-forwarding kernel
!
router ospf 1
   router-id 10.255.10.12
   passive-interface default
   no passive-interface Ethernet1
   max-lsa 12000
!
router ospfv3
   router-id 10.255.10.12
   !
   address-family ipv6
!
end
