! spine-e - Baseline Configuration
! Role: spine, DC: east

hostname spine-e

! Management
service routing protocols model multi-agent
management api http-commands
   no shutdown

! Local user for eAPI access
username admin privilege 15 role network-admin secret admin123

! Global routing
ip routing
ipv6 unicast-routing

! Loopback
interface Loopback0
   ip address 10.255.30.1/32
   ipv6 address fd00:30::1/128

! P2P to l1-e
interface Ethernet1
   description to-l1-e
   no switchport
   mtu 9214
   ip address 10.1.20.0/31
   ipv6 address fd00:1:20::0/127

! P2P to l2-e
interface Ethernet2
   description to-l2-e
   no switchport
   mtu 9214
   ip address 10.1.20.2/31
   ipv6 address fd00:1:21::0/127

! P2P to bl-e
interface Ethernet3
   description to-bl-e
   no switchport
   mtu 9214
   ip address 10.1.20.4/31
   ipv6 address fd00:1:22::0/127

! P2P to bl-e
interface Ethernet4
   description to-bl-e
   no switchport
   mtu 9214
   ip address 10.1.20.6/31
   ipv6 address fd00:1:23::0/127
