
> show running-config
! Command: show running-config at line 1
! device: spine-e (cEOSLab, EOS-4.35.1F-45319759.4351F (engineering build))
!
no aaa root
!
username admin privilege 15 role network-admin secret sha512 $6$CHi.0A4e0so9g2Ut$QIFXfYqVL0jyf9b.62WjjFrwVuab1HvVvxIySlQQzv6/aSyUU/jr9Vh781faYU7jzLXMnhT9n4CIxYXf1OZvq1
!
management api http-commands
   no shutdown
!
no service interface inactive port-id allocation disabled
!
service routing protocols model multi-agent
!
hostname spine-e
!
spanning-tree mode mstp
!
system l1
   unsupported speed action error
   unsupported error-correction action error
!
interface Ethernet1
   description to-l1-e
   mtu 9214
   no switchport
   ip address 10.1.20.0/31
   ipv6 address fd00:1:20::/127
   ip ospf network point-to-point
   ip ospf area 0.0.0.0
   ospfv3 ipv6 network point-to-point
   ospfv3 ipv6 area 0.0.0.0
!
interface Ethernet2
   description to-l2-e
   mtu 9214
   no switchport
   ip address 10.1.20.2/31
   ipv6 address fd00:1:21::/127
   ip ospf network point-to-point
   ip ospf area 0.0.0.0
   ospfv3 ipv6 network point-to-point
   ospfv3 ipv6 area 0.0.0.0
!
interface Ethernet3
   description to-bl-e
   mtu 9214
   no switchport
   ip address 10.1.20.4/31
   ipv6 address fd00:1:22::/127
   ip ospf network point-to-point
   ip ospf area 0.0.0.0
   ospfv3 ipv6 network point-to-point
   ospfv3 ipv6 area 0.0.0.0
!
interface Ethernet4
   description to-bl-e
   mtu 9214
   no switchport
   ip address 10.1.20.6/31
   ipv6 address fd00:1:23::/127
   ip ospf network point-to-point
   ip ospf area 0.0.0.0
   ospfv3 ipv6 network point-to-point
   ospfv3 ipv6 area 0.0.0.0
!
interface Loopback0
   ip address 10.255.30.1/32
   ipv6 address fd00:30::1/128
   ip ospf area 0.0.0.0
   ospfv3 ipv6 area 0.0.0.0
!
interface Management0
   ip address 172.20.20.28/24
   ipv6 address 3fff:172:20:20::1c/64
!
ip routing
!
ipv6 unicast-routing
!
router bgp 65300
   router-id 10.255.30.1
   no bgp default ipv4-unicast
   maximum-paths 4 ecmp 4
   neighbor EVPN peer group
   neighbor EVPN remote-as 65300
   neighbor EVPN update-source Loopback0
   neighbor EVPN ebgp-multihop 3
   neighbor EVPN route-reflector-client
   neighbor EVPN send-community extended
   neighbor 10.255.30.11 peer group EVPN
   neighbor 10.255.30.12 peer group EVPN
   neighbor 10.255.30.21 peer group EVPN
   !
   address-family evpn
      bgp next-hop-unchanged
      neighbor EVPN activate
!
router multicast
   ipv4
      software-forwarding kernel
   !
   ipv6
      software-forwarding kernel
!
router ospf 1
   router-id 10.255.30.1
   passive-interface default
   no passive-interface Ethernet1
   no passive-interface Ethernet2
   no passive-interface Ethernet3
   no passive-interface Ethernet4
   max-lsa 12000
!
router ospfv3
   router-id 10.255.30.1
   !
   address-family ipv6
!
end
